// Code generated by MockGen. DO NOT EDIT.
// Source: db/queries.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	db "bwa.com/hello/db"
	model "bwa.com/hello/model"
	gomock "github.com/golang/mock/gomock"
)

// MockQueries is a mock of Queries interface.
type MockQueries struct {
	ctrl     *gomock.Controller
	recorder *MockQueriesMockRecorder
}

// MockQueriesMockRecorder is the mock recorder for MockQueries.
type MockQueriesMockRecorder struct {
	mock *MockQueries
}

// NewMockQueries creates a new mock instance.
func NewMockQueries(ctrl *gomock.Controller) *MockQueries {
	mock := &MockQueries{ctrl: ctrl}
	mock.recorder = &MockQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueries) EXPECT() *MockQueriesMockRecorder {
	return m.recorder
}

// CloseSession mocks base method.
func (m *MockQueries) CloseSession() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseSession")
}

// CloseSession indicates an expected call of CloseSession.
func (mr *MockQueriesMockRecorder) CloseSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSession", reflect.TypeOf((*MockQueries)(nil).CloseSession))
}

// CreateTablesIfNotExist mocks base method.
func (m *MockQueries) CreateTablesIfNotExist() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTablesIfNotExist")
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTablesIfNotExist indicates an expected call of CreateTablesIfNotExist.
func (mr *MockQueriesMockRecorder) CreateTablesIfNotExist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTablesIfNotExist", reflect.TypeOf((*MockQueries)(nil).CreateTablesIfNotExist))
}

// VehicleQueries mocks base method.
func (m *MockQueries) VehicleQueries() db.VehicleQueries {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VehicleQueries")
	ret0, _ := ret[0].(db.VehicleQueries)
	return ret0
}

// VehicleQueries indicates an expected call of VehicleQueries.
func (mr *MockQueriesMockRecorder) VehicleQueries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VehicleQueries", reflect.TypeOf((*MockQueries)(nil).VehicleQueries))
}

// MockVehicleQueries is a mock of VehicleQueries interface.
type MockVehicleQueries struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleQueriesMockRecorder
}

// MockVehicleQueriesMockRecorder is the mock recorder for MockVehicleQueries.
type MockVehicleQueriesMockRecorder struct {
	mock *MockVehicleQueries
}

// NewMockVehicleQueries creates a new mock instance.
func NewMockVehicleQueries(ctrl *gomock.Controller) *MockVehicleQueries {
	mock := &MockVehicleQueries{ctrl: ctrl}
	mock.recorder = &MockVehicleQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicleQueries) EXPECT() *MockVehicleQueriesMockRecorder {
	return m.recorder
}

// CreateVehicle mocks base method.
func (m *MockVehicleQueries) CreateVehicle(vehicle model.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVehicle", vehicle)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVehicle indicates an expected call of CreateVehicle.
func (mr *MockVehicleQueriesMockRecorder) CreateVehicle(vehicle interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVehicle", reflect.TypeOf((*MockVehicleQueries)(nil).CreateVehicle), vehicle)
}

// FindVehicle mocks base method.
func (m *MockVehicleQueries) FindVehicle(vin string) (*model.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVehicle", vin)
	ret0, _ := ret[0].(*model.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVehicle indicates an expected call of FindVehicle.
func (mr *MockVehicleQueriesMockRecorder) FindVehicle(vin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVehicle", reflect.TypeOf((*MockVehicleQueries)(nil).FindVehicle), vin)
}
