@startuml Class diagram


' HttpServer, Router, App

class HttpServer as "http.Server" <<external>> {
    + ListenAndServe()
}

class App as "app.App" <<app>> {
    + CloseSession()
}
class Router as "mux.Router" <<external>> {
    + HandleFunc(path, func)
}

class VehicleHandlers as "app.VehicleHandlers" <<handlers>> {
    + PostVehicle()
    + GetVehicle()
    + DeleteVehicle()
}

HttpServer -down-> Router
App o-left-> Router
App o-down-> VehicleHandlers : route


' Queries

interface Queries as "db.Queries" <<db>> {
	+ CreateTablesIfNotExist()
	+ CloseSession()
	+ VehicleQueries()
}

interface VehicleQueries as "db.VehicleQueries" <<db>> {
	+ CreateVehicle()
	+ FindVehicle()
	+ DeleteVehicle()
}

interface UserQueries as "db.UserQueries" <<db>> {
	+ CreateUser()
	+ FindUser()
}
remove UserQueries

App o-down-> Queries
VehicleHandlers -down-> Queries
Router -[hidden]right- Queries
Queries o-> UserQueries
Queries o-right-> VehicleQueries
UserQueries -[hidden]down- VehicleQueries
UserQueries -[hidden]down- VehicleQueries


' Scylla

class ScyllaQueries as "scylla.Queries" <<db>>
class ScyllaSession as "gocqlx.Session" <<external>>

Queries <|-down- ScyllaQueries
ScyllaQueries o-left-> ScyllaSession


' Legend

!$appColor = "#ec3c13"
!$dbColor = "#1b91db"
!$handlersColor = "#71b32b"
!$externalColor = "#787878"

legend right
|= |= <color:#000000>Legend  \n|
|<color:$appColor>■</color>| <color:#333333>app |
|<color:$handlersColor>■</color>| <color:#333333>handlers |
|<color:$dbColor>■</color>| <color:#333333>db / scylla |
|<color:$externalColor>■</color>| <color:#333333>external |
endlegend


' Appearance

hide stereotype
hide class fields
hide interface fields
Skinparam shadowing false

hide annotation circle

skinparam {
	BackgroundColor #f2f2f2
	RoundCorner 10
	Padding 2
	
	ArrowColor #787878
	ArrowThickness 2
}

skinparam class {
	BorderThickness 2
	BackgroundColor #ffffff
	AttributeFontColor #2f2f2f
	AttributeFontSize 10
	FontSize 12
	FontStyle "bold"

	FontColor<<app>> $appColor
	BorderColor<<app>> $appColor

	FontColor<<handlers>> $handlersColor
	BorderColor<<handlers>> $handlersColor

	FontColor<<db>> $dbColor
	BorderColor<<db>> $dbColor

	FontColor<<external>> $externalColor
	BorderColor<<external>> $externalColor
}

skinparam legendBackgroundColor #ffffff
skinparam legendBorderColor #4c4c4c
skinparam LegendFontColor #ffffff
skinparam LegendFontSize 11

@enduml
