@startuml Class diagram


' HttpServer, Router, App

class HttpServer as "http.Server" <<external>> {
    + ListenAndServe()
}

class App as "app.App" <<app>> {
    + CloseSession()
}
class Router as "mux.Router" <<external>> {
    + HandleFunc(path, func)
}

class VehicleHandlers as "routing.VehicleHandlers" <<routing>> {
    + PostVehicle()
    + GetVehicle()
    + DeleteVehicle()
}

annotation routing as "routing.*" <<routing>> {
	+ Route()
}

HttpServer -down-> Router
App o-left-> Router
App .down.> routing
routing .> VehicleHandlers : route
routing .[norank].> Router


' Database

interface Database as "db.Database" <<db>> {
	+ CreateTablesIfNotExist()
	+ CloseSession()
	+ VehicleDAO()
}

interface VehicleDAO as "db.VehicleDAO" <<db>> {
	+ CreateVehicle()
	+ FindVehicle()
	+ DeleteVehicle()
}

interface UserDAO as "db.UserDAO" <<db>> {
	+ CreateUser()
	+ FindUser()
}
remove UserDAO

App o-down-> Database
VehicleHandlers -down-> Database
Router -[hidden]right- Database
Database o-> UserDAO
Database o-right-> VehicleDAO
UserDAO -[hidden]down- VehicleDAO
UserDAO -[hidden]down- VehicleDAO


' MockDB

class MockDB as "mockdb.Database" <<db>>

Database <|-down- MockDB


' Legend

!$appColor = "#ec3c13"
!$dbColor = "#1b91db"
!$routingColor = "#71b32b"
!$externalColor = "#787878"

legend right
|= |= <color:#000000>Legend  \n|
|<color:$appColor>■</color>| <color:#333333>app |
|<color:$routingColor>■</color>| <color:#333333>routing |
|<color:$dbColor>■</color>| <color:#333333>db / mockdb |
|<color:$externalColor>■</color>| <color:#333333>external |
endlegend


' Appearance

hide stereotype
hide class fields
hide interface fields
Skinparam shadowing false

hide annotation circle

skinparam {
	BackgroundColor #f2f2f2
	RoundCorner 10
	Padding 2
	
	ArrowColor #787878
	ArrowThickness 2
}

skinparam class {
	BorderThickness 2
	BackgroundColor #ffffff
	AttributeFontColor #2f2f2f
	AttributeFontSize 10
	FontSize 12
	FontStyle "bold"

	FontColor<<app>> $appColor
	BorderColor<<app>> $appColor

	FontColor<<routing>> $routingColor
	BorderColor<<routing>> $routingColor

	FontColor<<db>> $dbColor
	BorderColor<<db>> $dbColor

	FontColor<<external>> $externalColor
	BorderColor<<external>> $externalColor
}

skinparam legendBackgroundColor #ffffff
skinparam legendBorderColor #4c4c4c
skinparam LegendFontColor #ffffff
skinparam LegendFontSize 11

@enduml
