@startuml Class diagram

hide stereotype
hide class fields
hide interface fields
skinparam shadowing false

skinparam class {
	BackgroundColor #ffeeee
	ArrowColor #444444
	BorderColor #444444

	BackgroundColor<<external>> #dddddd
	BorderColor<<external>> Gray

	BackgroundColor<<db>> #c9e2ff
	BorderColor<<db>> #5c5c5c
}

skinparam legendBackgroundColor #ffffff
skinparam legendBorderColor #4c4c4c
skinparam LegendFontColor #ffffff
skinparam LegendFontSize 14

class HttpServer as "http.Server" <<external>> {
    + ListenAndServe()
}

class App {
    + CloseSession()
    - createVehicle()
    - deleteVehicle()
}
class Router as "mux.Router" <<external>> {
    + HandleFunc(path, func)
}

HttpServer -down-> Router
App o-left-> Router

interface Queries as "db.Queries" <<db>> {
	+ CreateTablesIfNotExist()
	+ CloseSession()
}

interface VehicleQueries as "db.VehicleQueries" <<db>> {
	+ CreateVehicle()
	+ FindVehicle()
}

interface UserQueries as "db.UserQueries" <<db>> {
	+ CreateUser()
	+ FindUser()
}

class ScyllaQueries as "db ScyllaQueries" <<db>>

Queries o-> UserQueries
Queries o-right-> VehicleQueries
UserQueries -[hidden]down- VehicleQueries

class ScyllaSession as "gocqlx.Session" <<external>>

App o-> Queries
UserQueries -[hidden]down- VehicleQueries
ScyllaQueries o-left-> ScyllaSession

Queries <|-down- ScyllaQueries

Router -[hidden]right- Queries

legend left
|= |= <color:#000000>Legend  \n|
|<color:#ff6666>■</color>| <color:#333333>top level |
|<color:#6666ff>■</color>| <color:#333333>db |
|<color:#aaaaaa>■</color>| <color:#333333>external |
endlegend

@enduml