@startuml Class diagram

skinparam shadowing false

skinparam class {
	BackgroundColor White
	ArrowColor #444444
	BorderColor #444444

	BackgroundColor<<External>> #dddddd
	BorderColor<<External>> Gray
}

class HttpServer as "http.Server" <<External>> {
    + ListenAndServe()
}

class App {
    + CloseSession()
    - createVehicle()
    - deleteVehicle()
}
class Router as "mux.Router" <<External>> {
    + HandleFunc(path: String, f: func)
}

interface Queries as "db.Queries" {
	+ CreateTablesIfNotExist(): error
	+ CloseSession()
	+ CreateVehicle(vehicle: model.Vehicle): error
	+ FindVehicle(vin: string): (*model.Vehicle, error)
}

class Vehicle as "model.Vehicle" {
	+ Vin: string
	+ EngineType: string
	+ EvData: *EvData
}

class EvData as "model.EvData" {
	BatteryCapacityInKwh: int
	SocInPercent: int
}

Queries ---> Vehicle
Vehicle *-down-> EvData

class ScyllaQueries as "db.ScyllaQueries"
class ScyllaVehicle as "db.ScyllaVehicle"

ScyllaQueries .do.> ScyllaVehicle

HttpServer -down-> Router

App o-left-> Router
App o-> Queries
App ---> Vehicle
Queries <|-- ScyllaQueries

Router -[hidden]right- Queries

ScyllaVehicle .left.> Vehicle : from/to

Vehicle -[hidden]right- ScyllaVehicle

@enduml