name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04

    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: make
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
    - name: Unit tests
      run: make unit-tests
    - name: Integration tests
      run: make integration-tests

